name: palace
version: 0.0.1+2
description: build server side dart applications with expressjs like framework but with batteries included
homepage: https://github.com/maxzod/
# publish_to: "none"
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http_server: ^1.0.0
  meta: ^1.3.0
  # to validate route matching
  path_to_regexp: ^0.4.0
  yaml: ^3.1.0
  # classes to ease access to http-server utils
  mime_type: ^1.0.0
  palace_validators: ^0.0.3
  path: ^1.8.0

dev_dependencies:
  pedantic: 1.11.0
  test: ^1.16.8
  dio: ^4.0.0
  http:
