name: palace
version: 0.0.0-alpha.0
description: Dart Server Side framework
homepage: https://github.com/maxzod/
environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lint: ^1.5.3
dependencies:
  meta: ^1.3.0
  path_to_regexp: ^0.4.0
