name: palace
version: 0.0.1+3
description: build server side dart applications with ExpressJs like framework
  but with batteries included
homepage: https://github.com/maxzod/
publish_to: "none"
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ansicolor: ^2.0.1
  meta: ^1.3.0
  mime_type: ^1.0.0
  mysql1: ^0.19.0
  # palace_body_parser: ^1.0.0+1
  palace_validators: ^0.0.3
  path: ^1.8.0
  path_to_regexp: ^0.4.0
  yaml: ^3.1.0

dev_dependencies:
  dio: ^4.0.0
  pedantic: 1.11.0
  test: ^1.16.8
