name: palace
version: 0.0.0-alpha.1
description: Dart Server Side framework
homepage: https://github.com/maxzod/
# publish_to: "none"
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0
  # # palace_validators:
  # # git:
  # # url: https://github.com/maxzod/palace_validators.git
  path_to_regexp: ^0.4.0
  yaml: ^3.1.0

dev_dependencies:
  lint: ^1.5.3
