name: core
version: 0.0.1
description: minimal server side dart micro-framework for building REST api easily
homepage: https://github.com/maxzod/palace
environment:
  sdk: ">=2.12.0 <3.0.0"
publish_to: "none"
dependencies:
  mime_type: ^1.0.0
  router:
    path: ../router

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
